### ISSUE TITLE
Impossible de VALIDER Commande

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#100]
Exemple 90757, impossible de valider la commande

**Comment by MamboJoel** [comment]
Comme le montre ce printscreen il s'agit d'une commande de vente LGI. 

![image](https://cloud.githubusercontent.com/assets/3832009/20942059/eeb0087e-bbf9-11e6-8984-16ed6c4029e2.png)

Elle correspond au [KartID=30907](http://lgivm.waybis.com/Kart/Form.aspx?KartID=30907)
