### ISSUE TITLE
Lecture Onglet Commande

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#102]
Lorsque nous rentrons dans une commande est-ce possible que toute la partie supérieure, à savoir récap (Livraison, acheteur...) + les onglets Commande, Bon de Commande et Suivi, soient lisibles même si on scrowl down sur la page?
Selon les garçon cela leur gagnera du temps à la lecture et vérification des commandes

**Comment by MamboJoel** [comment]
On a effectué des modifications pour que l'entête de commande demeurent visibles après le scroll.
