### ISSUE TITLE
Bug accès commandes Projets et autres statuts

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#103]
Je viens de créer le compte de Dominique Mauriac chez le fournisseur Barat. Je me rends compte qu'elle a accès à toutes nos commandes en projet.
Peux-tu vérifier et faire en sorte qu'elle n'ait plus accès aux commandes en statut Projet / reçu / facturée / annulée?

**Comment by MamboJoel** [comment]
Je ne reproduis pas. Je m'authentifie entant que Dominique Mauriac et j'obtiens ce formulaire :

![image](https://cloud.githubusercontent.com/assets/3832009/22174568/1cd1cf56-dfe2-11e6-94e3-3eaf30be2655.png)

Et ce formulaire ne permet pas d'afficher les commandes en projet. Peux-tu préciser le scénario ou clore ?
