### ISSUE TITLE
Suivi Commande - Bug

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#104]
Cf cdde# 90846, les messages de suivi sont vides alors que les personnes ayant communiqué ont rentré des infos

**Comment by MamboJoel** [comment]
NB : Tu peux faire une capture d'écran et directement faire Ctrl-V ici. Comme ça :

![image](https://cloud.githubusercontent.com/assets/3832009/20940860/8800a2d2-bbf4-11e6-963a-4e62f646b094.png)

Je te conseille (comme aux imprimeurs ou autres) d'utiliser l'outil de capture d'écran windows qui permet de dessiner une sélection. Comme là :

![image](https://cloud.githubusercontent.com/assets/3832009/20941018/0ae91f80-bbf5-11e6-8ab2-784b64e6db59.png)

Cette image montre que je ne reproduis pas l'anomalie. J'ai pu envoyer un message avec les identifiants de de Virginie Moreau. Comme on fait de nombreux travaux et mises à jour il arrive que le service soit down pendant quelques secondes. En particulier vers 14h comme on le voit sur son impression d'écran, je constate des erreurs dans les logs dus à une mise à jour.
