### ISSUE TITLE
RECEPTION - Devis à générer par Nicolas

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#105]
Nicolas,
Suite à notre conversation de ce soir, merci de faire un devis par rapport au développement et à l'activation du statut 'Recu' dans le nouveau module d'appro.
A savoir, que nous avons besoin de répliquer à l'identique ce qui existe sur l'ancien module Waybis.
Merci

**Comment by celinelgi** [comment]
Nicolas,
Ci-joint les Cahier des Charges pour mise en place du développement des réceptions.
Merci de nous apporter une réponse rapidement afin que nous puissions nous rendre disponibles.
Merci
[CDC_Gestion_Commandes_RECEPTIONS_LGI.pdf](https://github.com/lgi-wines/Approvisionnements/files/713454/CDC_Gestion_Commandes_RECEPTIONS_LGI.pdf)
[Schema_Page_Reception.pdf](https://github.com/lgi-wines/Approvisionnements/files/713453/Schema_Page_Reception.pdf)

**Comment by lgazeau** [comment]
Nicolas,
Suite ta demande nous t'avons laissé tranquille sur Janvier.
Rappel : Sommes OK sur les facturations de dépassements "validés" et sur le principe d'un facturation trimestrielle.
Par rapport à ce module, déterminant dans notre relations aux imprimeurs, il nous faut désormais ton chiffrage et caller ensemble un timing court pour RECEPTION et FACTURATION.
Appelle nous (Céline/Moi) pour faire un point d'ici vendredi, après avoir reprise son cahier des charges du 18 01 17
Merci d'avance.
A ta disposition.

**Comment by MamboJoel** [comment]
Tu peux m'appeler dans l'après-midi.

**Comment by MamboJoel** [comment]
[NTLM Technologies - Devis 20170102 - Réception des approvisionnements.pdf](https://github.com/lgi-wines/Approvisionnements/files/788494/NTLM.Technologies.-.Devis.20170102.-.Reception.des.approvisionnements.pdf)

**Comment by MamboJoel** [comment]
Nous avons avancé et publié ce développement.
Dans le [module d'approvisionnement](http://ui.lgi.ntlm.technology), conformément au devis, vous trouverez :

- De nouveaux critères de recherche : Code LGI, commandes partielles, non conformes.
- Pour chaque commande un onglet Réception qui permet de créer des bons de réception et de déclarer des non conformités.

Il est probable qu'il vous soit nécéssaire de vider le cache pour obtenir ces nouveautés.
