### ISSUE TITLE
Bug Compte Aurélien

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#108]
Aurélien Troutaud ne peut rien faire depuis son compte, peux-tu regarder?

**Comment by MamboJoel** [comment]
L'accès LGI à l'outil de suivi de devis nécessite d'avoir deux autorisations :

- Ecriture des composants
- Gestion des produits

![image](https://cloud.githubusercontent.com/assets/3832009/20972590/a0d521ec-bc95-11e6-91f7-667b7814d3ce.png)

J'ai paramétré le compte d'Aurélien Troutaud.

**Comment by celinelgi** [comment]
Ces cases sont cochées dans son compte ca devrait marcher

**Comment by MamboJoel** [comment]
> J'ai paramétré le compte d'Aurélien Troutaud.
