### ISSUE TITLE
problème composant étiquette à utiliser

### ISSUE THREAD

**Issue by LEBRUNPhilippe** [lgi-wines/Approvisionnements#109]
Nicolas,

J'ai un problème sur le stock du composant Contre Etiquette BSC 11C-3 (à 13%vol) ID=16650 .
J'ai une quantité à utiliser alors que je n'ai pas de mise en bouteille à produire.
Est-ce que tu peux éliminer ce Pb, stp?

Merci.

Philippe

**Comment by MamboJoel** [comment]
Je regarde.

**Comment by MamboJoel** [comment]
La mise [178888](http://lgivm.waybis.com/Manufacturing/Form.aspx?ManufacturingID=178888) doit produire 4 200 unités de ComponentID=16650 au 16/12/2016.
Je m'étonne que tu ne l'ais pas trouvée. C'est sans doute une autre anomalie.

**Comment by MamboJoel** [comment]
Philippe : s'il te plaît n'ouvre pas une nouvelle issue à chaque message. Le principe de Github est qu'une problème égale une issue. Cela permet de suivre l'état d'un problème sous forme d'un fil de discussion. Par exemple ici, recevant ton message de ce soir, j'ai voulu remonter le fil de la discussion et je me suis apperçu que ton issue était vierge, que c'était une nouvelle issue et qu'elle doublonnait donc avec l'initiale, celle-ci, la 109.

Aussi, demain, dans un mois, ou dans un an, si on rencontre une situation connexe et qu'on remonte dans les archives tous les échanges seront concentrés au même endroit, dans la même issue.

Quand un problème est réglé, son issue est fermée. Elle peut être réouverte si le problème surgit à nouveau. Alors je ferme l'issue #115 et je colle ici ton message. Enfin ces issues sont reliées à notre code source, et permettent de le documenter avec les contributions lisibles en français des uns et des autres, comme tes messages et les miens.

Ecrit par @LEBRUNPhilippe dans la #115 :

> Nicolas,
> 
> Il doit en effet y avoir une anomalie car quand je vais sur la mise 178888, le composant qui est chargé sur le produit a la même référence BCS 11C-3 mais pas le même ID=21283.
> Ce qui différencie les deux composant est le degré d'alcool présent sur la contre étiquette, il est de 13°5 pour l'ID 21283 alors qu'il est de 13° sur l'ID=16650 que j'avais mentionné dans mon premier message.
> Il y a peut être eu une manip faite au niveau du service d'Eric qui a provoqué ce blocage, j'espère que tu sauras nous débloquer ça. Merci.
> A ta disposition.
> 
> Philippe

**Comment by MamboJoel** [comment]
J'ai corrigé la mise. J'ai fait pointé son Input sur le 21283. 

Tu peux constater les stocks disponibles du [21283](http://lgivm.waybis.com/Component/Stock.aspx?ComponentID=21283) et du [16650](http://lgivm.waybis.com/Component/Stock.aspx?ComponentID=16650).

Je pense que la mise a été créée quand le produit pointait sur le 16650. Puis le service produit a pointé le produit sur le 21283. Il est possible que vous auriez pu rétablir la situation en supprimant la mise puis en la recréant.

Pour corriger j'ai dû faire quelques manipulations non orthodoxes dans la base de données. J'espère que vous n'aurez pas de problèmes demain matin. Sans quoi, n'hésitez pas à m'appeler.

Si le résultat est OK. Tu peux clore cette issue.

**Comment by LEBRUNPhilippe** [comment]
Nicolas,

Je pensais la problème résolu mais en allant vérifier d'autres composants je me suis aperçu que des infos avaient disparu dans les stocks.
Le système nous donne le stock réel mais les quantités "à recevoir" et " à utiliser" n'apparaissent plus.
De même, dans le tableau des alertes stock, il y a des composants en alerte qui n'apparaissent plus.

Merci d'avance.

Philippe

**Comment by MamboJoel** [comment]
Est-ce que tu peux me passer un ID de composant en anomalie, les quantités que tu attends et l'anomalie constatée ? Merci.

**Comment by LEBRUNPhilippe** [comment]
Composant ID=22053.
J'ai des quantités "à recevoir"= 6000 et "à utiliser"= 5970 qui ne sont pas visibles dans le stock du composant.
Merci

**Comment by MamboJoel** [comment]
Je vais simplement sur la page [stock du composant](http://lgivm.waybis.com/Component/Stock.aspx?ComponentID=22053) et je trouve ça :

![image](https://cloud.githubusercontent.com/assets/3832009/21011814/543a37c8-bd53-11e6-873e-97bfeca326a2.png)

Où trouves-tu une information contradictoire ( '"à recevoir"= 6000 et "à utiliser"= 5970') ? Tu peux me passer le lien de la page qui présente l'anomalie et/ou me faire une copie d'écran et la glisser ici.

Pour faire une copie d'écran tu peux trouver dans Windows l''Outil de capture d'écran" qui permet de dessiner une sélection ou simplement taper deux fois la touche "Impr écran". Puis tu tapes Ctrl-V directement dans la boîte qui permet d'écrire des message Github.

**Comment by MamboJoel** [comment]
Pour info Philippe : j'ai réussi à trouver un moyen d'exécuter la routine dans des délais acceptables. Peux-tu me dire si les quantités ont été recalculés comme attendu ?

**Comment by LEBRUNPhilippe** [comment]
Nicolas, Tout est OK. Merci.
Philippe

**Comment by MamboJoel** [comment]
Super. On clos.

Info technique :
```SQL
exec UpdateStockInventoryQuantities 0
```
Cette exécution est terriblement lente.
En revanche l'exécution du contenu de cette procédure stockée avec `@StockInventoryID = 0` est quasi immédiate.

**Comment by LEBRUNPhilippe** [comment]
Nicolas, je suis désolé de ré-ouvrir, tout est rentré dans l'ordre au niveau des stocks mais le problème d'origine est toujours là. l'ID=16650 est toujours en déficit à cause de la quantité "à utiliser"qui n'est associée à aucune commande.

Philippe

**Comment by MamboJoel** [comment]
Je regarde.

**Comment by MamboJoel** [comment]
C'est corrigé. Très étrange ce cas. Je suis pas vraiment satisfait de mon correctif. Hésite pas à réouvrir si le problème survient à nouveau.
