### ISSUE TITLE
Impossible de télécharger pj. + suivi Cdde# 90846

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#110]
Ci-joint le fichier que Barat ne peut pas uploader.
![0044817eti-001](https://cloud.githubusercontent.com/assets/22617509/20971987/bb3abe04-bc93-11e6-8506-27f470fb684c.JPG)
[Uploading BAT_GRANDCHINI_116635.pdf…]()

**Comment by celinelgi** [comment]
vmoreau

**Comment by MamboJoel** [comment]
Je ne reproduis pas l'erreur :
- Je parviens à télécharger cette PJ avec mon compte.
- Egalement avec celui de Virginie Moreau.

Reproduis-tu l'erreur ? Quelle est l'anomalie constatée ?

![image](https://cloud.githubusercontent.com/assets/3832009/20972457/2e853172-bc95-11e6-98dd-780fcbeea571.png)

**Comment by celinelgi** [comment]
Ca bug depuis chez moi aussi 
![image](https://cloud.githubusercontent.com/assets/22617509/20972689/044c7716-bc96-11e6-941a-50c2aac2a2db.png)

**Comment by MamboJoel** [comment]
Peux-tu vider ton cache ?

**Comment by MamboJoel** [comment]
J'avais renommé le fichier avant de l'uploader. J'avais choisi un nom simple et ça a marché.
Le serveur refuse le fichier car il trouve le nom suspect, en particulier le caractère "%", qui permet à un hacker d'effectuer des injections malveillantes sur la machine.
Je peux :
- faire des recherches pour lever ce contrôle du serveur (et l'exposer à une faille de sécurité).
- faire des recherches sur les risques.
Comme tu veux. En attendant, pour vous débloquer, vous pouvez simplement retirer les caractères spéciaux des noms de vos fichiers.

**Comment by MamboJoel** [comment]
Est-ce que tu peux uploader ici le fichier BAT-GRA...635.pdf qui a levé l'erreur remontée sur ta copie d'écran ?

**Comment by celinelgi** [comment]
![0044817eti-001](https://cloud.githubusercontent.com/assets/22617509/20975951/4c85c5ea-bca1-11e6-977c-7315d2542573.JPG)
[Uploading BAT_GRANDCHINI_116635.pdf…]()

**Comment by MamboJoel** [comment]
Je pense que le problème vient du nommage de fichier. En effet, quand je le télécharge depuis github, je suis tenu de lui donner un nom, et je lui donne un nom simple. Ensuite il parvient à être uploadé sur lgi.

Pour des raisons de sécurité le serveurs LGI refusent les caractères spéciaux. Et peut-être même les espaces. Je recommande donc de les éviter.
