### ISSUE TITLE
Upload Pièces jointes

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#111]
Peux-tu prévoir de sélectionner plusieurs fichiers  à la fois lors d'insertion de pj?

**Comment by MamboJoel** [comment]
@Portekoi est-ce que tu peux te pencher sur ce cas ?

**Comment by Portekoi** [comment]
@MamboJoel Peux tu m'indiquer le chemin pour l'ajout d'une PJ? Je viens de regarder la commande "En Projet" n°88552 mais je ne vois pas où rajouter un document.(connecté avec le user Nicolas)

**Comment by Portekoi** [comment]
OK, je pense avoir trouvé : c'est en cliquant sur "Suivi". Mais confirme au cas où. Merci.

**Comment by MamboJoel** [comment]
Oui c'est ça.

**Comment by MamboJoel** [comment]
C'est réglé.
