### ISSUE TITLE
Commandes en Statut PROJET

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#113]
Lorsque nous faisons une recherche uniquement sur ce statut, il y a plein de commandes qui remontent à 2009, peux-tu faire le ménage? car je ne sais d'où elles remontent

**Comment by Portekoi** [comment]
Archivage des commandes suivantes qui, je pense, sont des tests de @MamboJoel  :
48273
88439
88494
88495
88496
88497
88498
88499
88500
88503
88504
88506
88507
88508
88597
88631
88632
88707
90232
90235
90236
90237
90238
90239

**Comment by Portekoi** [comment]
Query : 

update [Order] set LastStepName = 'Commande annulée' where ID in(
   Select o.ID 
 From [Order] o Left Join OrderItem On o.ID = OrderItem.OrderID Where 1 = 1  And SellerType =
  'Waybis.Pinard.Supplier, Waybis.Pinard' And (1=2  Or LastStepName = 'projet') 
  and ((SellerID = 4 and buyerID = 2) and o.LastStepUserID = 1)


  )

**Comment by Portekoi** [comment]
Ajout : 
87264
87265
87266
87267
87271
87275
87280
87397
87399
87402
87403
87405
87406
87407
87408
87409
87410
87412
87416
87418
87754
87755
87756
87757
87759
87762
87764
87766
87769
87778
87780
87894
87896
87897
87898
87899
87916
87919
87920
87921
87924
87927
87929
87932
87937
87939
87940
87941
87944
87948
87949
87952
87953
87954
87955
87956
87957
87958
87959
87960
87962
87964
87965
87966
87967
87975
87977
87980
87981
87982
87983
87984
87985
87986
87987
87988
87989
87990
87991
87992
87993
87994
87995
88002
88004
88007
88008
88009
88010
88011
88012
88013
88014
88023
88025
88035
88037
88081
88082
88083
88084
88085
88086
88088
88089
88090
88091
88092
88097
88098
88099
88101
88102
88103
88104
88106
88107
88108
88109
88110
88111
88112
88113
88115
88122
88124
88127
88128
88129
88130
88131
88133
88140
88142
88152
88153
88154
88155
88159
88160
88161
88162
88163
88164
88165
88166
88167
88169
88170
88171
88172
88174
88176
88182
88184
88185
88187
88188
88189
88190
88192
88193
88194
88195
88197
88199
88205
88207
88208
88210
88211
88212
88213
88214
88215
88216
88217
88218
88219
88220
88223
88224
88225
88226
88230
88236
88237
88240
88241
88242
88243
88245
88247
88253
88255
88259
88261
88262
88263
88264
88265
88266
88267
88268
88272
88282
88289
88291
88348

SQL  : 
update [Order] set LastStepName = 'Commande annulée' where ID in(
   Select distinct o.ID 
 From [Order] o Left Join OrderItem On o.ID = OrderItem.OrderID Where 1 = 1  And SellerType =
  'Waybis.Pinard.Supplier, Waybis.Pinard' And (1=2  Or LastStepName = 'Projet') 
    and o.[TotalWithTax] = 18 and o.LastStepUserId is null and o.OrderDate < '2016-09-01'
  )

**Comment by Portekoi** [comment]
48780
49184
49651
50745
50848
50849
50850
51069
52225
52226
52227
52228
60201
66710
73547
78251
78677
86915
86916
86917
87277
87765
87774
88221
88222

update [Order] set LastStepName = 'Commande annulée' where ID in(
   Select distinct o.ID 
 From [Order] o Left Join OrderItem On o.ID = OrderItem.OrderID Where 1 = 1  And SellerType =
  'Waybis.Pinard.Supplier, Waybis.Pinard' And (1=2  Or LastStepName = 'Projet') 
    and o.[TotalWithTax] = 0 and o.LastStepUserId is null and o.OrderDate < '2016-09-01'
  )

**Comment by Portekoi** [comment]
je pense avoir nettoyé tous les "projet" de @MamboJoel

**Comment by MamboJoel** [comment]
Merci. Je clos.
