### ISSUE TITLE
Alertes Emails

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#114]
Chaque utilisateur reçoit un email suite à chacune de ses actions de changement de statut ou de commentaire.
Objectif: ne plus recevoir d'alerte email lorsque l'utilisateur est à l'origine de l'action.
En revanche chaque utilisateur devra continuer à recevoir les alertes correspondantes aux statuts sélectionnés dans leur compte utilisateur

**Comment by MamboJoel** [comment]
OK.

**Comment by celinelgi** [comment]
Les alertes suites aux actions menées par les utilisateurs sont de retour. Ex: cdde 91904, Romain a envoyé à l'imprimeur et donc a reçu une alerte email suite à son action.
Peux-tu regarder?
Merci
