### ISSUE TITLE
Mise 178888

### ISSUE THREAD

**Issue by LEBRUNPhilippe** [lgi-wines/Approvisionnements#115]
Nicolas,

Il doit en effet y avoir une anomalie car quand je vais sur la mise 178888, le composant qui est chargé sur le produit a la même référence BCS 11C-3 mais pas le même ID=21283.
Ce qui différencie les deux composant est le degré d'alcool présent sur la contre étiquette, il est de 13°5 pour l'ID 21283 alors qu'il est de 13° sur l'ID=16650 que j'avais mentionné dans mon premier message.
Il y a peut être eu une manip faite au niveau du service d'Eric qui a provoqué ce blocage, j'espère que tu sauras nous débloquer ça. Merci.
A ta disposition.

Philippe

**Comment by MamboJoel** [comment]
#109
