### ISSUE TITLE
Bug Saisie de commentaires

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#116]
Cdde# 91166 Muriel depuis son compte n'arrive pas à insérer et envoyer un commentaire, alors que depuis le compte d'Aurélien cela fonctionne très bien sur la même commande.
C'est la deuxième fois qu'elle rencontre ce problème.

**Comment by MamboJoel** [comment]
Je ne reproduis pas :

![image](https://cloud.githubusercontent.com/assets/3832009/21398480/c23bea88-c7a7-11e6-977e-e508d01fdb5a.png)

Est-ce qu'elle a d'autres éléments pour que je reproduise l'anomalie ?

**Comment by celinelgi** [comment]
Nicolas,
Il semblerait que Muriel rencontre régulièrement des problèmes, voir ci-dessous description:

''Tout ce passe bien avec : Envoyée à l’imprimeur + EXE  
Mais voici le bug lors de l’envoi avec choix
- envoyée à l’imprimeur 
si je coche : empêcher cette page de …..
j’ai une roue de travail qui ne s’arrête pas
![bug_muriel](https://cloud.githubusercontent.com/assets/22617509/22058155/3ca41518-dd68-11e6-9178-8b8493f121c1.png)

**Comment by MamboJoel** [comment]
Il me faudrait le scénario pour reproduire l'anomalie. Les étapes qui conduisent à lever cette erreur. Par exemple avec une commande en particulier.
Car je ne reproduis rien avec son authentification.

**Comment by MamboJoel** [comment]
Je propose qu'elle installe teamviewer et qu'elle m'appelle quand elle rencontre ce problème. Je regarderai alors l'état de sa session dans Chrome.

**Comment by MamboJoel** [comment]
Scénario :
- Se loguer avec Muriel par TV
- cmd 91832
- Envoyer à l'imprimeur

L'erreur dans la console Chrome : 

![image](https://cloud.githubusercontent.com/assets/3832009/22287079/ca78bdba-e2f1-11e6-9ae4-2c497f1c0388.png)

**Comment by MamboJoel** [comment]
On a trouvé.

- L'envoi à l'imprimeur implique la validation du bon de commande.
- La validation d'un fichier (bon de commande ou devis) nécessitait d'avoir l'accès à la gestion des approvisionnements.
- Historiquement la gestion des approvisionnements nécessite d'avoir les accès "Ecriture des composants" et "Validation des produits" :
![image](https://cloud.githubusercontent.com/assets/3832009/22297901/023a2ac2-e31f-11e6-803a-6905b47b0f91.png)
- Muriel n'avait pas la Validation des produits.

En lui accordant cet accès ça a réglé le problème.

Mais au fond elle n'est pas gestionnaire d'approvisionnement. Donc je lui ai retiré l'accès "Validation produits", et j'ai changé le droit nécessaire pour valider un document (Bon de commande ou devis). Il faut désormais être gestionnaire d'approvisionnements ou PAO. Ça n'est pas non plus une solution parfaite. Il faudrait des droits pour chaque type de document (BdC, Devis, etc.) mais est-ce sage à ce stade d'opter pour une gestion si fine ?

Par ailleurs elle me parle d'un problème de mails qu'elle ne recevrait pas ou qui ne partirait pas. Mais je ne retrouve pas l'issue. Elle devrait peut-être s'inscrire sur github. Si elle s'inscrit, qu'elle me passe le login qu'elle a choisi et je lui envoie une invitation à ce projet.
