### ISSUE TITLE
BUG - Facturation sur ancien module

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#117]
Nicolas,
Toutes les commandes en statut reçu sur l'ancien module Waybis sont 'figées', à savoir que nous ne pouvons pas les passer en statut facturé, ni même ajouter des commentaires, modifier des prix/quantités...
Peux-tu vérifier?
Merci,
Céline

**Comment by MamboJoel** [comment]
Je ne reproduis pas. J'ai réussi à passer en statut facturé la [90084](http://lgivm.waybis.com/Order/Reception.aspx?OrderID=90084) qui était en reçue.

![image](https://cloud.githubusercontent.com/assets/3832009/22064589/80ef1bca-dd84-11e6-84ee-85815cfdacb0.png)

Peux-tu me donner un numéro de commande afin que je reproduise ?

**Comment by celinelgi** [comment]
On a le problème sur toutes les commandes ''Reçues'' (ex: 89504), on ne peut pas saisir le numéro de la facture, des commentaires, la date de facture...
Pour l'archivage/historique il est nécessaire de rentrer ces données avant de passer en statut 'Facturé'

**Comment by Portekoi** [comment]
@MamboJoel Si je ne dis pas de bêtises, c'est sur cette page :
http://lgivm.waybis.com/Order/Form.aspx?OrderID=89504

Le statut est "reçue" mais ce qui passe à "True" la propriété "isFrozen".

Si je regarde pourquoi cela retourne True, je vois la méthode "FrozenSteps" qui retourne true pour les états :
* Validée
* Commande reçue
* Commande facturée
* Commande annulée

Solution : sur l'écran de facture, même si la commande est "Frozen", autoriser la saisie de certaines données sensibles pour la facturation comme le commentaire, la date de facture et le numéro de facture.

**Comment by Portekoi** [comment]
Sur la nouvelle interface, l'état de la commande 89504 est modifiable sans souci en "Facturée" mais je ne vois pas où saisir comme sur l'ancienne interface, le commentaire, la date de facture et le numéro de facture.

**Comment by celinelgi** [comment]
Normal, ce n'est pas encore développé sur le nouveau module

**Comment by celinelgi** [comment]
nous comptons le développer dans le foulée de la phase réception

**Comment by Portekoi** [comment]
OK merci. Donc il faut corriger cela sur l'ancienne interface.
