### ISSUE TITLE
COMMANDES // Commentaire Interne

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#120]
Faire apparaître dans chaque commande une zone 'Commentaire Interne' accessible uniquement aux utilisateurs LGI du service Produit (surtout pas aux imprimeurs, embouteilleurs...!!!!!)
A insérer en haut de l'écran de la commande à droite

**Comment by celinelgi** [comment]
Attention n’apparaît pas dans l'onglet réception

**Comment by MamboJoel** [comment]
Est-ce que tu peux préciser de quel commentaire il s'agit (il y en a de nombreux, composant, ligne de commande, commande, etc.). Je pense qu'il s'agit de celui de la commande. Par exemple [celle-ci](http://lgivm.waybis.com/Order/Form.aspx?OrderID=94171) :

![image](https://cloud.githubusercontent.com/assets/3832009/25898179/44d5cf08-358b-11e7-95ba-bc6b6b9d9ba1.png)

Si c'est bien ce commentaire, tu dis qu'il remonte coté onglet "Commande" mais pas coté onglet "Réception" ?

**Comment by celinelgi** [comment]
erreur de ma part le commentaire apparaît bien lorsque renseigné, le commentaire interne concerné est celui contenu dans le formulaire du composant (cf. screen shot ci-dessous)
**Cependant il ne faut pas que ce commentaire soit visible par des utilisateurs autres que LGI**
![image](https://cloud.githubusercontent.com/assets/22617509/26314451/4b8ec89a-3f0e-11e7-89d5-31bf5b27cbcf.png)

**Comment by MamboJoel** [comment]
C'est bon.
Avec mon compte on voit le commentaire :
![image](https://cloud.githubusercontent.com/assets/3832009/26328952/5a7dae98-3f45-11e7-9a30-d6aee32a6bf3.png)
Avec celui de Jean-Paul Mes on ne le voit plus :
![image](https://cloud.githubusercontent.com/assets/3832009/26328983/703e78e8-3f45-11e7-94c7-469559da13d5.png)
