### ISSUE TITLE
Bug acces commande depuis alerte email

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#123]
A priori le lien d'acces à la commande depuis l'alerte email ne fonctionne pas cela donne un message d'erreur 403.6

**Comment by MamboJoel** [comment]
Est-ce que tu peux me transférer le mail par email ?

**Comment by MamboJoel** [comment]
C'est corrigé. Ce sera donc valide pour les prochains mails envoyé.
