### ISSUE TITLE
Joindre fichier autre que JPEG /PDF

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#124]
A priori Muriel/Aurélien ne peuvent pas joindre des fichiers .exe .ai ... dans le suivi???

**Comment by Portekoi** [comment]
Avec l'utilisateur "Nicolas", je ne peux pas non plus ajouter un .exe 

Avec quel utilisateur je peux tester l'ajout de ce type de fichier?

**Comment by celinelgi** [comment]
Tu peux essayer avec les utilisateurs Aurelien Troutaud et Muriel Frotey

**Comment by Portekoi** [comment]
Justement, dans votre premier message, vous indiquez :

> Muriel/Aurélien *ne* peuvent *pas* joindre des fichiers .exe

Donc : quel utilisateur peut actuellement le faire?

**Comment by celinelgi** [comment]
aucun...

**Comment by Portekoi** [comment]
Ok donc c'est une amélioration à apporter. Je ne trouve pas d'exemple de mail mais on ne peut pas envoyer des .exe dans les emails. C'est bloqué par la plus part des hébergeurs (Gmail, Yahoo, Hotmail) ainsi que les messageries type Outlook.

La seule solution serait de ne pas envoyer en pièce jointe les fichiers mais d'envoyer un lien pointant sur notre serveur pour que la personne la récupère. Je vais voir avec @MamboJoel

**Comment by celinelgi** [comment]
Ok ne pas poursuivre pour l'instant, ce n'est pas un besoin majeur.
