### ISSUE TITLE
Erreur de redirection entre les onglets "suivi" et "commande"

### ISSUE THREAD

**Issue by MamboJoel** [lgi-wines/Approvisionnements#125]
Message original de Romain :

> Depuis ce matin, dès que nous faisons une action sur l'onglet "suivi" d'une commande (changement de statut, commentaire,...), le système nous redirige directement sur l'onglet "commande", ce qui n'était pas le cas auparavant.
> Cela nous oblige à retourner sur l'onglet "suivi" après chaque action

**Comment by MamboJoel** [comment]
C'est corrigé.

**Comment by RomainLGI** [comment]
Attention, à priori ce n'est pas corrigé. Ça continue à le faire à cet heure ci

**Comment by MamboJoel** [comment]
F5 ou vider le cache.
