### ISSUE TITLE
Bouton ''+Nouveau Bon de réception''

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#128]
Lorsque je clique sur ce bouton rien ne se passe en apparence... cependant toute l'appli bug et je ne peux plus rien faire, même revenir sur le dashboard principal bug (à savoir que je n'ais plus accès aux statuts)

**Comment by MamboJoel** [comment]
C'est corrigé. Je m'aperçois que le dernier déploiement à planté à mi-parcours. Je refais une mise à jour générale.
