### ISSUE TITLE
Lignes Quantité commandée / à recevoir...

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#129]
Lignes Quantité commandée et à recevoir ne sont pas logique, cf. exemple cdde# 90512 qtt cddée = 35 000 et qtt à recevoir = 45000
Peux-tu m'expliquer la logique que tu as implémenté derrière? 
La qtt à recevoir doit être égale  à celle commandée sauf si livraison partielle

**Comment by MamboJoel** [comment]
C'est parce que 90512 n'est pas la seule commande en attente pour ce composant.
La commande [90510](http://ui.lgi.ntlm.technology/order/90510) attend 10000 unités de ce composant.

**Comment by celinelgi** [comment]
Ok bien compris - cependant après discussion avec le service produit ce mode de lecture n'est pas clair, d'autant que ceci sera utilisé par des personnes extérieures à LGI. Il faut faire apparaître la ligne ''Quantité à recevoir'' dans le cas ou la commande a été livré partiellement afin d'identifier au premier coup d'oeil le manquant à recevoir.
Dans mes schémas de pages, on souhaitaient voir l'inventaire de stock, à savoir qtt en stock + qtte à utiliser
