### ISSUE TITLE
Fournisseur - Envoi de plusieurs fichiers à la fois

### ISSUE THREAD

**Issue by MamboJoel** [lgi-wines/Approvisionnements#13]
Prévoir le téléchargement de JPEG avec les BAT de la part des imprimeurs

**Comment by MamboJoel** [comment]
**Changement de l'expression du besoin :**
Envoyer plusieurs fichier à la fois.

**Comment by celinelgi** [comment]
Est-ce possible d'uploader plusieurs fichiers en même temps? à savoir sélectionner dans l'explorateur plusieurs fichiers simultanément et cliquer sur joindre

**Comment by MamboJoel** [comment]
Certainement, il faut faire une recherche. En revanche ça appartient vraiment à la Milestone de démonstration à l'imprimeur ?

**Comment by celinelgi** [comment]
Oui car ce sont les imprimeurs qui vont utiliser cette fonction en téléchargeant leurs BAT/Devis

**Comment by MamboJoel** [comment]
Cette entrée est en doublon avec https://github.com/lgi-wines/Approvisionnements/issues/111

**Comment by MamboJoel** [comment]
Et la #111 traite cette amélioration depuis le 25 janvier. Y a-t-il un problème ?
