### ISSUE TITLE
Compte Utilisateur - Stephanie Pilaz

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#131]
J'ai créé un compte pour Stéphanie Pilaz de la société Paul Sapin qui est un embouteilleur. Dans les paramètres je l'ai taguée en Embouteilleur et Fournisseur. Cependant, depuis son compte je n'arrive pas à consulter les commandes qui la concerne, commande à retrouver # 93492
ID: spilaz // MDP: XXXXXX

A quoi est reliée cette notion? acheteur / destinataire / fournisseur / embouteilleur??

**Comment by MamboJoel** [comment]
Céline, il vaut mieux ne pas livrer pour le moment de mot de passe ici, cet espace github n'est pas encore sécurisé.

**Comment by MamboJoel** [comment]
Dans un premier temps j'ai complété [les droits de Stéphanie Pilaz](http://lgivm.waybis.com/User/Form.aspx?UserID=180) avec ceux que j'ai constaté chez d'autres utilisateurs embouteilleurs, en particulier "Visulisation des composants" et "Accès en écriture" :

![image](https://cloud.githubusercontent.com/assets/3832009/24933638/95d3606c-1f17-11e7-9ebd-d051bcea031b.png)

Seulement elle n'avait toujours pas accès à [la commande 93492](ui.lgi.ntlm.technology/order/93492). Et c'est normal car cette commande est à destination de [l'entrepôt Paul Sapin](http://lgivm.waybis.com/Warehouse/Form.aspx?WarehouseID=12). Et cet entrepôt n'appartient pas à l'embouteilleur Paul Sapin mais à LGI :

![image](https://cloud.githubusercontent.com/assets/3832009/24933756/44e7d1e6-1f18-11e7-99ed-e958c03f8944.png)

J'ignore si ce paramétrage est voulu, alors je ne prends pas l'initiative de le modifier. Tu peux tester de ton coté ? En affectant cet entrepôt à l'embouteilleur Paul Sapin ?
