### ISSUE TITLE
Suivi - Réception

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#132]
Les bons de réception ou Non Conformités n'apparaissent pas dans le suivi?
exemple cdde# 90512

**Comment by MamboJoel** [comment]
Tous les quantités de cette commande n'ont pas été reçues.

**Comment by celinelgi** [comment]
Tu n'as pas répondu à ma question... pourquoi les actions menées au niveau des réceptions ne sont pas visibles dans le suivi?

**Comment by MamboJoel** [comment]
C'est ok : le suivi se met à jour.
