### ISSUE TITLE
Réception surplus

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#134]
Bien vu que je peux réceptionner des quantités supérieures à celles commandées. Cependant, comment gères-tu ces surplus?
Parfois ils sont gratuits, parfois ils doivent être valorisés au tarif négociés de la commande. Ceci à un impact important à la fois sur la gestion de stock et du reporting.

De plus, en cas de surplus il faudrait un popup qui signale que nous allons réceptionner plus que prévu, est-ce normal???

**Comment by MamboJoel** [comment]
Ces questions seront traitées dans [le projet de facturation](https://github.com/lgi-wines/Approvisionnements/issues/106).
