### ISSUE TITLE
Statut à créer

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#136]
Peux-tu créer un statut ''Reçu / NC'' ce statut permettra de mettre la commande dans un statut temporaire qui permettra aux embouteilleurs d'identifier clairement les commandes non conformes sur lesquelles ils doivent assurer un suivi jusqu'à ce que la NC soit corrigée.

**Comment by Portekoi** [comment]
Quelles actions seront permises sur ce nouveau statut?

**Comment by celinelgi** [comment]
Ce statut permettra aux embouteilleurs de rechercher directement qu'elles commandes sont NC et donc sur lesquelles des actions sont en cours (ex: en attente livraison manquant, reimpression car étiquette livrée NC...)

**Comment by MamboJoel** [comment]
Inflation de statuts. NC est un propriété booléenne de la commande.

**Comment by celinelgi** [comment]
Donc qu'est-ce qu'on fait?
