### ISSUE TITLE
Partielles? Non Conformes?

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#138]
Je ne comprends pas l'utilisation?

**Comment by MamboJoel** [comment]
Je vérifie des cas de sécurité en liaison avec [l'issue pour Silvie Pilaz](https://github.com/lgi-wines/Approvisionnements/issues/131) et qui relève l'application extranet. J'ai rangé les issues [dans ce projet](https://github.com/lgi-wines/Approvisionnements/projects/2) en glissant dans la colonne "Recette" les issues qui me semblaient urgentes pour la livraison de l'outil. On travaille dessus aujourd'hui.

Je te rappelle dans la matinée pour répondre à la question de la présente issue, et aussi celle sur [les statuts](https://github.com/lgi-wines/Approvisionnements/issues/136).

**Comment by MamboJoel** [comment]
Ok pour tout ça. On a changé le listing.
