### ISSUE TITLE
Moteur de recherche - filtre par date à recevoir

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#140]
Est-ce que nous pouvons faire une recherche des commandes du jour à recevoir? à savoir aujourd'hui je veux voir tout ce qu'il y a à recevoir aujourd'hui?
Il faudrait pouvoir sélectionner le statut VALIDE et entrer la date rechercher.

Car à ce jour le moteur de recherche ne prend en compte que les dates de création de la commande, n'est-ce pas?

**Comment by MamboJoel** [comment]
- Ajouter le choix de la date sur lequel appliquer les bornes (Date de commande, date de livraison souhaiter) :
![image](https://cloud.githubusercontent.com/assets/3832009/26835160/e48f0cba-4ad7-11e7-94bd-27ab83614edf.png)

**Comment by MamboJoel** [comment]
C'est développé, tu peux tester et clore ?

**Comment by celinelgi** [comment]
Peux-tu modifier l'intitulé ''Type de date'' par ''Recherche calendrier''
et dans le déroulant remplacer par
- Date de commande
- Date de réception

**Comment by MamboJoel** [comment]
Ok !

**Comment by MamboJoel** [comment]
On a borné la période sélectionnée pour inclure les deux jours sélectionnés.
