### ISSUE TITLE
Compte Utilisateur - Sindy Prouchet

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#141]
Voir compte de Sindy Prouchet
Elle a uniquement ''UCC'' comme embouteilleur tagué, cependant elle voit aussi les commandes à recevoir de Sapin par exemple: #93022 (sapin) / 93320 (CJA)

**Comment by MamboJoel** [comment]
J'ai trouvé.

Le temps et l'évolution ds besoin nous donnent aujourd'hui une gestion des droits sibylline. Il y a deux droits qui, lorsqu'un utilisateur les cumule, fait que l'application le considère comme membre de LGI :

- Ecriture des composants	
- Gestion des produits	

Alors je te propose de retirer au moins un de ces droits (Gestion des produits) aux utilisateurs embouteilleurs.

**Comment by celinelgi** [comment]
Parfait! j'ai modifié
