### ISSUE TITLE
Intitulé Bon de réception vs Bon de livraison

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#142]
Il faudrait uniformiser les notions de Bon de livraison et de bon de réception, peux-tu corriger les entrées ''Bon de livraison #...'' par ''Bon de réception #...'' afin que cela corresponde au bouton ''+ Nouveau Bon de réception''

**Comment by MamboJoel** [comment]
OK !

**Comment by celinelgi** [comment]
Après F5, ça ne marche pas...
![image](https://cloud.githubusercontent.com/assets/22617509/24962632/c03ebc40-1f9c-11e7-81df-fc96b6d6d377.png)

**Comment by MamboJoel** [comment]
C'est bon.

**Comment by celinelgi** [comment]
Non il y a toujour Bon de Livraison #...
