### ISSUE TITLE
# Bon de réception

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#143]
Le numéro qui suit le # des Bons de réception créé ne redémarre par de 0 sur les commandes, il semblerait qu'il redémarre suite au dernier bon de livraison émis même si c'est pour une autre commande...
Ex: # 90510 il y un seul bon de réception, mais il a le numéro 12 - je n'ai pas annulé de bon de réception sur cette commande

**Comment by celinelgi** [comment]
# numéro de commande - numéro bon de réception => exemple # 94754-1 / # 94754-2...

**Comment by MamboJoel** [comment]
- Ajouter un champ `DeliveryReceipt.Reference `de type entier qui est incrémenté à chaque nouveau bon de réception **de la commande**. (Et non de l'item de commande.)
- A l'écran le présenter selon le nommage suivant : `{Order.ID}-{DeliveryReceipt.Reference}`.

**Comment by MamboJoel** [comment]
On a effectué ce développement. Tu peux tester et clore ?

**Comment by celinelgi** [comment]
Perfect!
