### ISSUE TITLE
BUG - Reception Totale et partielle

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#144]
Cdde# 93352 / 93497
Nous ne pouvons pas faire de réception, les essais ont été menés depuis le compte de Nancy Pena et le mien.

**Comment by Portekoi** [comment]
@celinelgi Je ne maitrise pas encore ce projet. J'ai accès au menu réception mais ensuite, quel(s) bouton(s) avez vous cliqué?

**Comment by celinelgi** [comment]
Bouton ''réception totale''

**Comment by Portekoi** [comment]
@MamboJoel De ce que je vois, c'est un `Article` qui est à nul dans la commande et lève une exception : 

`Cannot insert the value NULL into column 'ArticleType', table 'Pinard.dbo.DeliveryReceipt'; column does not allow nulls. INSERT fails.`

Une fois identifié sur v1 : http://lgivm.waybis.com/api/order/recieve-all.aspx?OrderID=93352

Mais je ne vois pas laquelle provoque cette erreur. Beaucoup de bons de réception ont `0` dans `Attendu` et `Reçu` ce qui ne me parle pas.

**Comment by MamboJoel** [comment]
@celinelgi tu ne me remontes pas l'anomalie constatée. Je suppose que c'est une question d'autorisation. Je n'ai pas beaucoup de moyens ce soir pour déboguer. Mais, ça m'a rappelé [cette issue](https://github.com/lgi-wines/Approvisionnements/issues/141).
Si pour [Syndy Prouchet](http://lgivm.waybis.com/User/Form.aspx?UserID=140) l'accès embouteilleur fonctionne, il n'y a pas de raison qu'il ne fonctionne pas pour [Nancy Pena](http://lgivm.waybis.com/User/Form.aspx?UserID=182) si on leur confère des droits similaires.

J'ai ajouté à cette dernière "Accès en écriture" et j'ai pu effectuer une réception totale de la [93497](http://ui.lgi.ntlm.technology/order/93497). 

![image](https://cloud.githubusercontent.com/assets/3832009/25362589/371ed676-2955-11e7-9ed0-fc5ed75b7b56.png)

Quant à la [93352](http://ui.lgi.ntlm.technology/order/93352) toutes les quantités étaient déjà reçues. J'ai simplement passé le statut en "Commande reçue".
