### ISSUE TITLE
RECEPTION - Bug lié aux frais

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#146]
Ex cdde# 93231 / 93297...
Ces commandes sont bien reçues dans nos entrepôts, de plus les réceptions des habillages sont bien créditées dans le système, cependant ces commandes ne passent pas en statut 'reçu' car il y a des frais qui subsistent et sont en attente de réception, cependant nous ne pouvons pas les réceptionner...
Comment faire? 
Ces frais sont inhérents aux commandes, le cas se reproduit sur un grand nombre de nos commandes et ces frais ne font pas l'objet d'une livraison, ils permettent de prendre en charge des dépenses liées à l'impression

**Comment by MamboJoel** [comment]
Je ne reproduis pas, j'ai pu passer la commande en reçue :
![image](https://cloud.githubusercontent.com/assets/3832009/25363392/609b4b60-295a-11e7-8c5b-afe254001bb1.png)

**Comment by celinelgi** [comment]
cependant lorsqu'il y a des frais et que nous réceptionnons les composants, les frais ne sont pas recptionnables du coup la commande reste en Validé et commande partiellement reçue

**Comment by MamboJoel** [comment]
Ce cas est traité.
