### ISSUE TITLE
Accès aux commandes en statut ''Reçu''

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#147]
Sindy Pourchet ne peux pas accéder aux commandes en statut ''reçu'', est-ce possible d'ouvrir l'accès aux utilisateurs embouteilleurs.

**Comment by MamboJoel** [comment]
Je ne reproduis pas. Je m'authentifie avec ses accès, constate qu'elle peut chercher les commandes reçues, recherche celles-ci et obtiens cela :
![image](https://cloud.githubusercontent.com/assets/3832009/25363748/43d647b6-295d-11e7-9ada-f8d4f6ec5bb6.png)
