### ISSUE TITLE
Liste Non Conformités

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#149]
Par défaut le critère ''autre'' est rempli dans le champ Non Conformité du bon de réception, est-ce possible de ne rien faire remonter par défaut?
Car dans la majorité des cas non réception conformément à la commande

**Comment by MamboJoel** [comment]
Il suffit de ne pas ajouter de non conformité.
Note qu'on ajoute des non conformités en cliquant sur le bouton "+ Ajouter" : 
![image](https://cloud.githubusercontent.com/assets/3832009/25363011/ddb2fd80-2957-11e7-91e8-e696f2c4b84b.png)

Et qu'il est toujours possible de les supprimer après la création du BR :
![image](https://cloud.githubusercontent.com/assets/3832009/25363019/f8381faa-2957-11e7-8f09-bff3d7e61d1f.png)

... ou d'en ajouter :
![image](https://cloud.githubusercontent.com/assets/3832009/25363033/140fe4ce-2958-11e7-941d-c416bc3189bc.png)

**Comment by celinelgi** [comment]
Afficher le formulaire de NC après un clic @Portekoi

**Comment by MamboJoel** [comment]
J'avais réglé aussi ce cas. @Portekoi tu peux regarder le patch Angular2 du commit que je viens de poster.
@celinelgi il est possible que ça nécessite F5 ou ctrl-F5.
