### ISSUE TITLE
Annulation Bon de réception => statut cdde

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#151]
Ex cdde# 90510 commande réceptionnée en plusieurs fois puis bon de réception # 198 annulé, la commande n'est pas revenue en statut ''validée'
Il faut que ça soit le cas car la commande n'est pas entièrement reçue

**Comment by MamboJoel** [comment]
C'est très compliqué. Car cela exigerait que l'embouteilleur puisse passer une commande en statut "validée".

C'est ce que j'essayais de t'expliquer la dernière fois : le principe des statuts de commande n'est pas cohérent. Il implique une linéarité immuable entre les statuts qui ne reflète pas la vie réelle d'une commande, et que les statuts sont exclusifs des autres. Et c'est le cas ici : une commande est validée. Puis quand elle est reçue, elle est marquée comme reçue et non pus validée. Or elle est toujours validée dans les faits.
Il aurait mieux valu attribuer des propriétés binaires qui affirment si oui on non une commande est validée, si oui ou non elle est réalisée, etc.

Compte tenu de notre modèle de statut, pour passer la commande en Validée, il te faut donner accès à la validation des commandes à l'embouteilleur.
