### ISSUE TITLE
Réception commande de Repiquage

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#152]
Cdde# 93639
Lorsque Sindy réceptionne totalement la commande cela crédite le stock de la référence Vierge du même nombre que celui à recevoir...
Leval Pinot Noir VIERGE doit être débitée de 1497 étiquettes qui vont venir s'ajouter au stock de Leval Pinot Noir 2015, cependant les deux composants sont crédités de 1497 étiquettes, il faut que ce soit uniquement Leval Pinot Noir 2015

**Comment by celinelgi** [comment]
Le bug ne se produit pas si réception partielle de la commande

**Comment by MamboJoel** [comment]
C'est corrigé.
