### ISSUE TITLE
RECEPTION bug compte Frederic Para (CJA)

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#155]
A priori l'utilisateur n'arrive pas à réceptionner la commande ci-dessous?
![image](https://cloud.githubusercontent.com/assets/22617509/25956995/8c02117e-366d-11e7-999d-0932c9b8bf4c.png)

**Comment by MamboJoel** [comment]
Je vois que Romain l'a reçue finalement. Je ne peux plus reproduire.

**Comment by MamboJoel** [comment]
Il faut donner des accès à l'utilisateur :

![image](https://cloud.githubusercontent.com/assets/3832009/26831473/b7591a84-4acc-11e7-8f9b-825790201483.png)
