### ISSUE TITLE
Cdde # 94076 - Bug réception totale

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#158]
Réception totale effectuée par Romain et Eric à plusieurs reprises cf. screen shot ci-dessous
![image](https://cloud.githubusercontent.com/assets/22617509/26639726/edc9f6c0-4625-11e7-8168-fece190126c8.png)

Sur le composant CHV 01C pas de problème, en revanche sur CHV 01E la réception c'est créditée dans le stock à plusieurs reprises cependant à la lecture de l'onglet réception la réception n'est pas faite cf screen shot ci-dessous
![image](https://cloud.githubusercontent.com/assets/22617509/26639809/21378c2a-4626-11e7-8d08-2e4cb0a9e4b6.png)

**Comment by MamboJoel** [comment]
Je ne m'explique pas ce phénomène, je ne parviens pas à reproduire.
Les BR ont des quantités nulles alors que leurs mouvements respectifs ont une quantité positive. Je trouve étonnant aussi que les mouvements aient été si proches dans le temps.

**Comment by MamboJoel** [comment]
L'erreur venait du paramétrage de l'entrepôt SOBEMAB qui n'a pas de propriétaire. L'erreur 500 stipulait :

>     Exception message: L'entrepôt SOBEMAB n'a pas de propriétaire. Veuillez le définir dans l'onglet formulaire.
