### ISSUE TITLE
Moteur de recherche - filtre par destination

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#159]
Est-ce possible d'ajouter dans les critères de recherche un champ ''Livraison''?
Certains membres de mon équipe qui travaillent sur plusieurs centres d'embouteillage en ont besoin afin de faire des tris par embouteilleurs.
Merci d'avance

**Comment by MamboJoel** [comment]
C'est développé, tu peux tester et clore ?

**Comment by celinelgi** [comment]
On dirait que ça bug... cf impr écran il y a un pop up
![image](https://user-images.githubusercontent.com/22617509/27225747-e011ac94-529b-11e7-86fd-e5844d770dcc.png)

**Comment by MamboJoel** [comment]
C'est corrigé.
