### ISSUE TITLE
Cdde # 93435 - Gestion de stock suite annulation Bon de réception

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#160]
On est embêté aujourd’hui parce que l’annulation du bon de réception sur cette commande n’avait pas défalqué le stock (je parle bien du stock et pas du reliquat cette fois). Du coup on pensait avoir 20000 étiquettes de plus que ce qu’on a vraiment. Il me semble que tu avais pris des notes à ce sujet lors de notre formation. On décale des mises en attendant une nouvelle commande d’habillage.
Je ne sais plus si j’ai fait depuis d’autres annulations de bons de réception, mais je te tiendrai au courant si le problème réapparait

**Comment by MamboJoel** [comment]
Je pense que tu fais référence à le #133 
Mais je ne reproduis pas le problème : l'annulation d'un BR retire le stock comme attendu.
