### ISSUE TITLE
Insertion commentaire dans suivi

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#161]
Cdde# 94614 - l'utilisateur n'arrive pas à insérer de commentaire dans le suivi, il reçoit le message d'erreur ci-dessous.
J'ai essayé de rentrer un commentaire depuis son compte et je n'ai pas eu de message d'erreur.
Peux-tu vérifier?

![image](https://user-images.githubusercontent.com/22617509/26927979-79c5fdb6-4c54-11e7-97e3-f23b36361321.png)

**Comment by MamboJoel** [comment]
Je n'ai pas d'erreur non plus... 
- Est-ce que l'erreur est levée systématiquement pour cet utilisateur ? 
- J'ai regardé dans les logs du jeudi 8 vers 14h10 (heure d'envoi du mail), mais je ne trouve aucune erreur.

**Comment by celinelgi** [comment]
A priori l'utilisatrice a eu le message d'erreur deux fois...
