### ISSUE TITLE
URGENT - Consultation cdde 94948

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#162]
Sur les comptes lrusque (Lydie Rusque) et babel (Bertrand Abel) je n'arrive pas à consulter la commande 94948 que je viens de créer
Je dois les voir demain matin à 10h.

J'ai revérifié le paramétrage des comptes utilisateurs + commande mais je ne comprends pas

**Comment by MamboJoel** [comment]
Céline, ces utilisateurs ont leurs accès correctement paramétrés à l'embouteilleur de la commande, 3S. Seulement pour accéder à la commande il faut qu'ils aient accès à [l'entrepôt de cette commande](http://lgivm.waybis.com/Warehouse/Form.aspx?WarehouseID=8)
![image](https://user-images.githubusercontent.com/3832009/27096773-7b443b9a-5072-11e7-9670-0ec9988d925e.png)
Or celui-ci appartient à LGI.

**Comment by MamboJoel** [comment]
J'ai désigné 3S comme propriétaire de cet entrepôt :
![image](https://user-images.githubusercontent.com/3832009/27097084-673e90c2-5073-11e7-8d6e-59bea96872f0.png)
Et l'utilisateur a désormais accès à la commande :
![image](https://user-images.githubusercontent.com/3832009/27097164-a865e15e-5073-11e7-864e-e3823ce0f5e3.png)
