### ISSUE TITLE
LGI-ORDERS dans la boucle des Appro

### ISSUE THREAD

**Issue by lgazeau** [lgi-wines/Approvisionnements#166]
La boîte E-mail   lgi-orders@lgi-wines.com  est dans la boucle des Appro, alors que cela ne devrait pas être le cas (voir PJ)

Pouvez-vous voir où est le bug ?
[LGI-ORDERS dans la boucle Appro.pdf](https://github.com/lgi-wines/Approvisionnements/files/1218046/LGI-ORDERS.dans.la.boucle.Appro.pdf)

**Comment by Portekoi** [comment]
Le mail semble être une réponse automatique dû à un message d'absence. Ce n'est pas l'application  qui l'a envoyé.
C'est le mail 'lgi-orders@lgi-wines.com ' qui a reçu la réponse d'absence car l'expéditeur du premier mail.
