### ISSUE TITLE
Fournisseur - Dashboard

### ISSUE THREAD

**Issue by MamboJoel** [lgi-wines/Approvisionnements#19]
Est-il possible d’avoir un Dashboard que nous ‘customiserions’ en fonction des impératifs de chacun ?
Attention, on conserve le bandeau Moteur de Recherche quoi qu’il en soit !
Exemple :
Utilisateur Romain de LGI : il souhaite vois directement toutes les commandes en statut ‘’Devis/BAT Publiés
Utilisateur Muriel de LGI : elle souhaite voir directement toutes les commandes en statut ‘’Envoyée + EXE’’ et ‘’Validation Graphique’’
Utilisateur Virginie de Barat (fournisseur) : elle souhaite voir toutes les commandes en statut ‘’Envoyée’’ et ‘’Envoyée+Exe’’ + ‘’Validée’’
Utilisateur Benoît de CJA (embouteilleur) : il devra voir toutes les commandes validées pour son entrepôt
Utilisateur Marjorie de UCC (embouteilleur à la facturation) : voir les commandes en statut ‘’reçue’’ afin qu’elle puisse les facturer

**Comment by MamboJoel** [comment]
C'est possible.
L'entrée #18 demandait une accessibilité des statuts spécifique si l'on est imprimeur. On est entrain de développer ça, et pour l'embouteilleur, LGI et la PAO. C'est à dire des statuts distribués en fonction de ton niveau d'accès.
Tu voudrais donc, un niveau supplémentaire, plus fin, lié directement à l'utilisateur ?
Il y aurait deux niveau

- L'un restrictif : on cache certains statuts selon les droits de l'utilisateur (par exemple le fournisseur ne voit pas "Projet")
- L'un optionnel : les préférence de chaque utilisateur parmi les statuts autorisés.

Merci de confirmer.

**Comment by celinelgi** [comment]
Je confirme les deux niveaux
