### ISSUE TITLE
Questions diverses sur les statuts

### ISSUE THREAD

**Issue by MamboJoel** [lgi-wines/Approvisionnements#23]
-   Commande reçue : le système de réception des commandes reste inchangé par rapport à l’actuel ? Il faut conserver la réception partielle ou totale.
-   Commande annulée : ce statut n’existant pas dans le système, il faut s’assurer qu’une fois la commande annulée les stocks prévus en commande seront bien annulés

**Comment by celinelgi** [comment]
Oui on conserve les notions de réception partielle et total
Commande annulée => oui il faut s'assurer que le système remet bien les stocks au propre

**Comment by MamboJoel** [comment]
Pour l'instant la réception et le stock restent inchangés.
