### ISSUE TITLE
Moteur de recherche : Mise en page

### ISSUE THREAD

**Issue by MamboJoel** [lgi-wines/Approvisionnements#24]
-	La couleur bleu qui surligne chaque ligne doit être différente en fonction de chaque statut afin d’optimiser la lisibilité, cf. ‘’TABLES_CORRESPONDANCES’’ onglet ‘ Statuts Commandes Appro’’
-	Espacer en colonne tous les intitulés qui sont en bout de ligne
-	Ajouter devant chaque ligne de composant le symbole correspondant au type de composant

**Comment by MamboJoel** [comment]
- ok.
- Je ne comprends pas la demande.
- ok.

**Comment by celinelgi** [comment]
espacer les infos suivantes: statut / date et heure de la création de la commande / auteur de la commande

**Comment by MamboJoel** [comment]
Ordonner en entête de table html l'entête des commandes.
