### ISSUE TITLE
Commandes - Récapitulatif

### ISSUE THREAD

**Issue by MamboJoel** [lgi-wines/Approvisionnements#25]
Ajouter :
o   Marque
o   Quantités commandées
o   Délai de livraison

**Comment by MamboJoel** [comment]
- ok.
- ok.
- Je ne trouve pas de "Délai de livraison" dans le modèle actuel. La page des commandes n'y fait pas mention : http://extranet.lgi-wines.com/Order/Form.aspx?OrderID=88366

**Comment by celinelgi** [comment]
Voir colonne ''Souhaité le''

**Comment by celinelgi** [comment]
Je pense qu'il faut enlever quantité commandée dans le récapitulatif car pas lisible, il faut juste rappeler la marque en commande
