### ISSUE TITLE
Validation des fichiers joints

### ISSUE THREAD

**Issue by MamboJoel** [lgi-wines/Approvisionnements#27]
Il faut insérer nos signatures électroniques, comment envisages-tu les choses ?

**Comment by MamboJoel** [comment]
Vous signez électroniquement la validation d'une commande lorsque vous la passez au statut VALIDEE
Est enregistré alors l'auteur de la validation et sa date.

**Comment by celinelgi** [comment]
Est-ce que cela apparaîtra sur les BAT?

**Comment by MamboJoel** [comment]
**Signature électronique**

Mail spécifique avec pompe. Contiendra le résumé du BAT.
ReplyTo à l'adresse de l'utilisateur qui a validé.
Signature du mail avec le nom de l'utilisateur qui a validé, etc.

Contient en PJ le dernier PDF. Et le cas échéant le devis numérique.

**Comment by MamboJoel** [comment]
Développement :

Outil de validation des documents : validation / dévalidation.

**Comment by MamboJoel** [comment]
Et lier le document à la ligne de commande.
