### ISSUE TITLE
Commandes - Ajout de nouveaux composants

### ISSUE THREAD

**Issue by MamboJoel** [lgi-wines/Approvisionnements#28]
"Ajout composant’’ comment est-ce que cela fonctionne ? est-ce pour ajouter des nouveaux composants à la commande ?

**Comment by MamboJoel** [comment]
L'ajout de nouveaux composants s'effectue via l'interface 
http://extranet.lgi-wines.com

**Comment by celinelgi** [comment]
Actuellement, nous ajoutons des nouveaux composants via l'interface évoquée, en allant dans l'onglet stock, en saisissant la quantité souhaitée et en sélectionnant la commande sur laquelle nous souhaitons mettre le composant => cette méthode n'est pas très lisible dès lors qu'il faut sélectionner une commande car uniquement le numéro et la date de commande sont visibles dans la liste déroulante
