### ISSUE TITLE
Réception / lecture des devis & BAT

### ISSUE THREAD

**Issue by MamboJoel** [lgi-wines/Approvisionnements#29]
-	Renommer ‘’Joindre un devis/BAT’’ par ‘’Vérifier BAT’’ (conserver ‘’Joindre un devis/BAT’’ dans l’interface amont)
-	Ouverture BAT : est-il possible d’ouvrir les BAT en scindant l’écran en 1/3 2/3 ? à savoir sur 1/3 l’appli Appro et 2/3 le BAT de l’imprimeur ?

**Comment by MamboJoel** [comment]
- Cette demande n'a pas de sens car ce bouton permet de JOINDRE un devis/BAT et non de l'OUVRIR (pour le vérifier comme tu dis)
- Je ne comprends pas la demande. L'ouverture d'un devis/BAT revient à télécharger le document. Il se trouve alors sur le disque et est ouvert via le logiciel idoine (Adobe Acrobat Reader, MS Word, etc)

**Comment by celinelgi** [comment]
ok
