### ISSUE TITLE
Cas du design des Devis / BAT par commande plutôt que par ligne de commande

### ISSUE THREAD

**Issue by MamboJoel** [lgi-wines/Approvisionnements#30]
La demande suivante relève à l'origine de l'affichage, mais soulève une profonde erreur de design :

> Ajouter en haut à gauche de chaque ligne composant une check box avec mention ‘’BAT validé’’ (comme tu as pu le constater on reçoit un BAT par composant de la commande, qui est à chaque fois signé individuellement même si renvoyé avec les autres BAT de la commande).

Le modèle a été conçu de manière à ce qu' un BAT/Devis est l'équivalent d'une commande. Il contient des lignes pour les différents articles de la commande à laquelle il répond.
Ainsi, pour une commande donnée, il n'existe qu'un seul BAT/Devis validé.

**Comment by celinelgi** [comment]
Comment fait-on lorsque nous recevons plusieurs BAT pour une même commande? Nous devons tous les signer - ou alors pouvons-nous fusionner les BAT et faire une seule signature?
Nos imprimeurs ne validerons pas nos commandes si il n'y a pas notre signature

**Comment by MamboJoel** [comment]
Ils publient des Devis / BAT via l'application en remplissant les cases de formulaire des articles commandés. Ils peuvent aussi publier un document correspondant.
Quand vous passez la commande en statut VALIDEE c'est que vous avez validé leur dernière publication.

**Comment by celinelgi** [comment]
Ok mais valider leur dernière publication ne fera pas preuve pour eux car c'est dans notre système => ils insistent pour voir notre signature sur le document

**Comment by MamboJoel** [comment]
Ils verront "VALIDEE"

**Comment by celinelgi** [comment]
Je crains que mes imprimeurs ne considèrent pas cela comme valable, ils veulent notre signature sur leur BAT

**Comment by MamboJoel** [comment]
Alors vous comptez l'imprimer et l'envoyer ?

**Comment by celinelgi** [comment]
Non, il existe la signature électronique - est-ce possible de l'insérer sur un PDF de BAT, ou autre support? on peut en discuter?

**Comment by MamboJoel** [comment]
Je ne connais pas ce procédé. Si tu en sais plus tu peux me désigner des ressources sur Internet ?

**Comment by celinelgi** [comment]
J'ai essayé ce procédé dans le cadre d'une réponse à un appel d'offre pour mon mari - en gros il a du adhérer à un organisme qui a certifié sa signature, et télécharger un plug-in qui ensuite a apposé sa signature sur son document de réponse

**Comment by celinelgi** [comment]
On n'a pas besoin de faire certifier nos signatures, mais l'idée c'était d'incruster nos signature + ''bon pour impression'' sur les BAT en PDF
