### ISSUE TITLE
Compte Imprimeur

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#31]
Est-ce qu’il faut que je crée les comptes imprimeurs dès demain ? comment ferons-nous le lien entre un imprimeur et la personne qui sera concrètement connectée ?
Exemple : actuellement dans la base de données nous avons rentré Barta, Imprimerie Estrabols… comme imprimeurs, à ces comptes fournisseurs il me faudra attribuer des utilisateurs, exemple Virginie Moreau pour Barat qui aura un accès dédié. En aucun cas cette personne ne devra avoir accès aux données concernant les autres imprimeurs, les embouteilleurs…

**Comment by MamboJoel** [comment]
Créer les utilisateurs.
