### ISSUE TITLE
Fournisseur - Lecture - échange sur composants de la commande

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#32]
#Composants
-	Supprimer commentaires du composant (ces commentaires sont internes, et ne doivent être visibles que par l’équipe LGI)
-	Supprimer : Quantité Reçue / Quantité par Lot / Prix / Total HT / Total TTC
-	Ajouter Bouton ‘’Modifier’’, ce bouton a pour but de permettre à l’imprimeur de venir nous informer des éventuelles incompatibilités techniques, pour se faire ce bouton l’amènera vers la page actuellement appelée ‘’Joindre un BAT’’, dans laquelle il pourra venir confronter ses données techniques différentes de celles contenues dans le composant d’origine. Attention, ceci à un but informatif, ce sera à nous de valider les corrections.
	Objectif : favoriser l’interactivité des échanges 
	La page ‘’Suivi’’ devra s’appeler ‘’Confrontation Composant’’
	Cette page permettra de voir un seul composant à la fois, afin d’éviter une erreur sur d’autres composants

**Comment by MamboJoel** [comment]
Ne plus ajouter de bouton "Modifier"
Fusionner les cases "Joindre un devis / BAT" et "Joindre un fichier".
