### ISSUE TITLE
Fournisseur - Données techniques commande

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#33]
Sens d’enroulement /  Mandrin /  Bobine => ces données sont actuellement contenues dans les BAT de nos imprimeurs, mais pas de notre côté alors que c’est nos embouteilleurs qui les imposent pour des raisons techniques.
Par conséquent, il faut les faire remonter directement sur nos bons de commande.
L’info source devra être contenue dans l’entrepôt du fournisseur sous la forme :
-	Sens d’enroulement : check box ou liste déroulante avec liste:
o	Extérieur droit
o	Extérieur gauche
o	Intérieur Droit
o	Intérieur gauche
-	 Mandrin : champ ouvert
-	 Bobine : champ oucert
Ces données devront être affichées directement dans le récap principal de la commande, à savoir dans le bandeau client/ fournisseur/livraison…

**Comment by MamboJoel** [comment]
Créer un champ de l'embouteilleur dédié à l'imprimeur.
Bottler.PrinterComment
