### ISSUE TITLE
Fournisseur - Ne devrait pas voir les statuts qui ne les concernent pas

### ISSUE THREAD

**Issue by lgazeau** [lgi-wines/Approvisionnements#38]
http://lgiui.waybis.com/person/158

**Comment by celinelgi** [comment]
Est-ce possible de cacher les statuts projet / facturé sur les moteurs de recherches des imprimeurs?

**Comment by MamboJoel** [comment]
C'est déjà le cas :

![image](https://cloud.githubusercontent.com/assets/3832009/20385864/757b9260-acb9-11e6-9bf4-d01f7da87ece.png)
