### ISSUE TITLE
Statuts

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#43]
Entre Waybis (ancien module) et le nouveau module Appro, les statuts ne se mettent pas à jour, cf. commande # 89994

**Comment by celinelgi** [comment]
Autre exemple commande # 89753 = Validé dans Waybis et Projet dans Appro => dans Appro elle doit être en VALIDE

**Comment by MamboJoel** [comment]
Nous avons traité le cas. Seulement ces commandes ont évolué en statut. Il s'agirait de tester sur des commandes encore en projet.
