### ISSUE TITLE
Waybis (ancien module) vers Appro (nouveau module)

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#44]
Nous avons décidé d'imposer une logique de création et de suivi de commande qui nous permet de ne 'quasiment' plus utiliser Waybis mais d'optimiser le module Appro.
Création de la commande: sélection du composant et choix des quantités => Waybis
Suivi/consultation commande (cf. Détail de la commande + Bon de Commande) => Appro

Par conséquent la consultation du Détail d'une commande et de son Bon de commande ainsi que les modifications, insertion de prix, changement de délai... TOUT devra se faire depuis le module APPRO
Ces notions doivent donc disparaître de Waybis cf. Détail de la commande + Bon de Commande

**Comment by MamboJoel** [comment]
Avant de supprimer ces fonctionnalité de l'application il faudra les implémenter coté approvisionnement.

**Comment by MamboJoel** [comment]
Je dois t'avouer, suis très chagriné que les composants de tests aient été supprimés, les 23004 et 23003.

**Comment by celinelgi** [comment]
Par erreur Eric les a supprimé... je suis désolée
Il a été prévenu de ne plus les toucher!
