### ISSUE TITLE
Moteur de Recherches - Statuts Exe

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#46]
Renommer par 'Envoyée à l'imprimeur + Exe'

**Comment by MamboJoel** [comment]
T'es certaine de ce changement ?
- Cela fait plusieurs fois que l'on renomme ces statuts.
- Il existe déjà un statut "Envoyé à l'imprimeur". Ça risque d'être confus non ? 
- Est-ce que ça ne cache pas un mal entendu sur le fonctionnement des statuts ?

**Comment by celinelgi** [comment]
Pas de malentendu, cela signifie que l'imprimeur reçoit la commande, et en parallèle Muriel/Aurélien doivent envoyer les fichiers d'exe
