### ISSUE TITLE
Logique Utilisation Commande dans APPRO

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#48]
APPRO devenant notre organe central de gestion et de suivi des commandes, il faut le rendre plus clair:
- Commande = détail de la commande + suivi (suppression d'un composant, modification d'un délai, d'un prix, insertion du prix devis, ajout / consultation des BAT & Devis)
- Suivi = détail des échanges, commentaires et actions qui ont eu lieu sur la commande => cet onglet est à titre informatif et servi uniquement pour la consultation et archivage de l'historique de la commande

A cette barre d'onglet actuelle il faudra ajouter d'autres fonctionnalités:
- Bon de commande => permet de générer un bon de commande PDF imprimable
- Changement de statut de la commande => c'est à ce niveau que nous choisirons de modifier le statu de la commande

**Comment by celinelgi** [comment]
Attention, actuellement c'est la page de Suivi qui s'ouvre en premier à l'ouverture d'une commande, il faut que ce soit désormais la page Commande qui contient le détail de la commande

**Comment by MamboJoel** [comment]
On a développé le passage des statuts sans message. 
Je ferme cette issue car j'ai créé une issue spécifique pour les pdf (  https://github.com/lgi-wines/Approvisionnements/issues/63 )
