### ISSUE TITLE
Commande  => Détail de la commande, lignes de composants

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#51]
Conserver présentation des lignes de composants avec les champs du formulaire de Waybis

Sur chaque ligne de composant ajouter les fonctionnalités:
- **Lien de renvoi vers le formulaire du composant** sous Waybis (pour d'éventuelles modifications) nommer le bouton 'Formulaire composant' => cette fonctionnalité sera accèssible uniquement aux utilisateurs LGI
- Visuel du composant => possibilité de cliquer dessus afin de le visualiser en plus grand
- Bouton 'Supprimer' => permettra de supprimer le composant de la commande => attention la quantité initialement commandée devra se déduire de la gestion de stock (cf. gestion actuelle dans Waybis)
- Zone 'Commentaire' : attention cette zone ne correspond en aucun cas au champ commentaire du formulaire du composant, cette zone est dédiée au suivi de la commande si nous avons besoin de faire un commentaire aux utilisateurs de la commande
- BAT/Devis : sur chaque ligne de composant les imprimeurs devront uploader le BAT/Devis correspondant à la ligne de composant de la commande,

**Comment by celinelgi** [comment]
Zone Commentaire + BAT/Devis => ne pas tenir compte
Par contre mettre en place les autres points

**Comment by MamboJoel** [comment]
Ok pour chaque point sauf le dernier pour lequel j'ai créé [une issue spécifique](https://github.com/lgi-wines/Approvisionnements/issues/78).
