### ISSUE TITLE
Commande => détail prix / quantité

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#54]
Pavé contenu dans colonne de droite sur chaque ligne de composant
- Souhaité le: la date doit être modifiable (en effet, nous la modifions en fonction du retour imprimeur ou de nos contraintes de production) => renommer par 'Délai de Livraison'
- Quantité par lot : à supprimer (est-ce que cela pose un problème de règle de calcul???)
- Prix du lot => renommer par Prix Budget
- Total HT => supprimer

Ajouter:
- Prix devis => champ ouvert dans lequel nous insérerons uniquement une valeur numérique, à savoir le prix négocié avec notre imprimeur
- Delta reporting : cette donnée est le delta prix budget versus prix devis sur l'année écoulée qui rassemble toutes les commandes sur cette référence (cf. Jacques sur outils de reporting)

Visibilité de ces champs:
- tous = utilisateurs LGI
- Prix Budget / Delta => ne doivent pas être visibles par d'autres utilisateurs que LGI

=> Imprimeurs et embouteilleurs auront accès uniquement à:
- Date de livraison
- Quantité
- Prix devis

**Comment by celinelgi** [comment]
Notions suivantes doivent être modifiables sur tous les statuts jusqu'au stade VALIDE:
- Date de livraison
- Quantité
- Prix devis (attention différent du prix budget)

**Comment by MamboJoel** [comment]
On a implémenté la modification des champs du détail de la commande.
Seulement je ne connais pas cette notion de "delta reporting". Elle n'existe pas dans l'application sur la page des commandes.

**Comment by celinelgi** [comment]
Attention, je vois sur le profil de Virginie, qu'elle peut voir nos prix budget, cf. cdde # 89994
Il ne faut surtout pas qu'elle ait accès à ces données car cela pourrait mettre en danger nos négo de prix
Cf commentaire d'entrée de l'issue 'Visibilité des champs''

**Comment by celinelgi** [comment]
Notion de Delta Reporting, ça a été mis en place avec Jacques dans le Reporting

**Comment by MamboJoel** [comment]
Virginie ne voit pas le prix budget dans la 89994.

La notion de delta reporting n'est pas disponible dans l'application. Je transmets à Jacques et je retirer le Milestone démo imprimeur.
