### ISSUE TITLE
Dashboard - lignes de commandes

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#57]
L'utilisateur qui remonte dans les lignes de commande est celui qui a créé la commande ou le dernier utilisateur a avoir mené une action sur cette commande?

**Comment by celinelgi** [comment]
Colonnes Total et ID sont à supprimer
Cf Wire Framing Dashboard pour nouvelle présentation colonnes

**Comment by MamboJoel** [comment]
C'est l'utilisateur responsable du dernier statut. Par exemple :

>  VALIDÉE le 09/11/2016 09:31 par  Eric ROURE

Supprimées les deux colonnes.
