### ISSUE TITLE
Bon de Commande

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#58]
Bon de commande devra être en version PDF
Il montrera le détail de la commande SANS:
- Prix Budget
- Prix Devis
- Delta Reporting
- Joindre un BAT
- Bouton Supprimer
- Formulaire composant

INSERER:
Signature + LOGO LGI
- Logo LGI en petit comme sur le bon de commande actuel
- Logo LGI + adresse => pied de page (cf. pj.)
- SIGNATURE: ce sera le prénom / nom + coordonnées de l'utilisateur qui a créé la commande

**Comment by celinelgi** [comment]
En lien avec l'issues # 63

**Comment by celinelgi** [comment]
Il manque ces infos
Logo LGI + adresse => pied de page (cf. pj.)
SIGNATURE: ce sera le prénom / nom + coordonnées de l'utilisateur qui a créé la commande

**Comment by celinelgi** [comment]
Enlever en haut du bon de commande ''Céline Boissard" Eric Roure... laisser juste Service Produit

**Comment by MamboJoel** [comment]
OK.
