### ISSUE TITLE
Suivi Commande

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#59]
Cette page a pour but unique d'être informative afin de visualiser tout ce qu'il s'est passé sur une commande.

Donc elle retracera du plus récent au plus ancien les échanges et actions.

Le mode de présentation actuel est parfait

ATTENTION: enlever les boutons 'Joindre un fichier ' et 'Joindre un devis/BAT'

**Comment by MamboJoel** [comment]
On a retiré le 'Joindre un devis/BAT' déjà.
Mais pourquoi retirer aussi  'Joindre un fichier' ? On ne joint plus de fichier ?
