### ISSUE TITLE
Bon de commande en PDF

### ISSUE THREAD

**Issue by MamboJoel** [lgi-wines/Approvisionnements#63]
Besoin exprimé dans #48

> Bon de commande => permet de générer un bon de commande PDF imprimable

**Comment by MamboJoel** [comment]
C'est un développement à part entière et qui concerne aussi l'ADV avec cette demande :

https://github.com/lgi-wines/Extranet-LGI/issues/12

Il nous faut trouver la bonne technologie.

**Comment by celinelgi** [comment]
Non cela ne concerne en rien l'ADV, car ces bons de commande sont uniquement pour l'usage de nos fournisseur

**Comment by MamboJoel** [comment]
Il s'agit de la même technologie et des mêmes objets et tables (order, orderitem, etc.)

**Comment by celinelgi** [comment]
Nous avions déjà un bon de commande qui se générait sur Waybis. N'est-ce pas la même chose mais en PDF et avec quelques infos en plus?

**Comment by MamboJoel** [comment]
C'est un bon de commande généré en html et non en pdf. Il s'agit d'effectuer des recherches pour trouver une technologie qui génère du pdf coté serveur, ou qui convertit html et css en pdf.

**Comment by MamboJoel** [comment]
On a trouvé une technologie compatible avec l'application. On va générer les pdf coté serveur. Il faut les réécrire entièrement car ça n'est pas une conversion depuis un fichier html existant. On commence avec le bon de commande approvisionnement qui te concerne. D'autant qu'il est le plus simple des documents LGI. 
On va imiter http://extranet.lgi-wines.com/Order/OrderDocument.aspx?OrderID=89994

**Comment by MamboJoel** [comment]
Si tu veux des modifications par rapport à ce modèle, il est préférable que tu nous les proposes avant que l'on soit trop avancé dans le développement.

**Comment by MamboJoel** [comment]
On a monté un premier document pour le bon de commande.
Il est envoyé dans le mail qui accompagne chaque passage à l'étape "Envoyé à l'imprimeur". Et dans le cas de l'annule et remplace aussi.

**Comment by celinelgi** [comment]
TOP le bon de commande! merci
Juste quelques petites modifications...
Enlever le terme ''coordonnées de/du'' avant Expéditeur et Destinataire
Modifier LGI Service Marketing par Service Produit LGI (sous expéditeur et en signature bas de page)

Pour l'expéditeur, toujours mettre Service Produit LGI sans nommer, ou alors si possible insérer le nom/prénom de la personne qui a envoyé la commande
