### ISSUE TITLE
Email Validation de commande

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#65]
Enlever ''pour un montant de xxx''

**Comment by lgazeau** [comment]
[Uploading Grille Planning partiels décembre 2016.pdf…](salut)

**Comment by lgazeau** [comment]
[Uploading Fichier XR 2016.11.08.xlsx…](sdflkjhsdlkjh)

**Comment by celinelgi** [comment]
Le montant apparait toujours dans l'intitulé 
Commande N°90420 du 14/11/2016 **450 €**

**Comment by MamboJoel** [comment]
Corrigé, cf #70
