### ISSUE TITLE
Moteur de Recherche // Marque

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#66]
Il faut prévoir de faire la recherche uniquement sur la base de la marque qui est renseignée dans Waybis, cf. Paramètres de Waybis ou nous créons les marques

**Comment by MamboJoel** [comment]
Ok pour ça.

**Comment by celinelgi** [comment]
Exemple : je rentre 'Mission' dans le champs de recherche dédié à la marque, dans le cadre de la présaisie il m'ouvre une liste de tous les composants comportant ce nom de marques
En fait, il faut uniquement voir le nom de marque, cela ne nous interesse pas de voirs tous les composants dans la liste
