### ISSUE TITLE
Commandes // Projet

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#67]
J'ai fait une recherche via le moteur de recherche: 
- Fournisseur = Barat
- Statut = Projet

Résultats
J'ai plein de commandes depuis le mois d'Août qui remontent en projet alors qu'elles sont validées voir même reçues, exemple # 89352

**Comment by MamboJoel** [comment]
Ce sont des reliquats. On a plusieurs fois changé le système des statuts. Je l'ai ai mis à jour à la main.
