### ISSUE TITLE
Modification Commande

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#68]
Cf. commande # 89994 qui était validée depuis le 08/11
J'ai souhaité la modifier en ajoutant un nouveau composant à la commande.
Chemin emprunté:
- Ancienne appli, je passe la commande en statut Validé à Projet afin de la retrouver dans mon pool de commandes modifiables
- J'ajoute mon composant (# 1775)
- Nouveau module d'appro, passe AUTOMATIQUEMENT la commande en statut 'Envoyée à l'Imprimeur' et renvoie la commande en ''Annule & Remplace''

Le cheminement est correct, cependant à aucun moment je n'ai pu revenir dans le nouveau module afin de faire d'éventuels ajustements. Exemple: lorsque j'ai passé ma commande en projet dans l'ancienne appli, je souhaitais ajouter non pas 1 composant mais 2 => or le module avait déjà renvoyé l'annule et remplace
Exemple 2: je souhaitais conserver temporairement la commande en Projet afin d'adjoindre un commentaire de suivi... je n'ai pas eu le temps de le faire

Conclusion!
Il faut pouvoir modifier les commandes en reprenant le main jusqu'au statut projet, une fois les modifications faites, il faut changer le statut et envoyer manuellement et non pas automatiquement.

**Comment by MamboJoel** [comment]
Les événements déclenchant l'objet de message "Annule et remplace" sont, lorsque la commande a déjà été envoyée à l'imprimeur :  
- L'ajout d'un item de commande
- La suppression d'un item de commande
- La modification du prix d'un item de commande
- La modification de la quantité d'un item de commande

Désormais à l'occasion de ces événements on n'envoie plus un message avec pour statut "Envoyé à l'imprimeur". Si la commande avait déjà été envoyée à l'imprimeur on l'enregistre. C'est donc à vous, après que vous avez déclenché un de ces événements de l'envoyer à l'imprimeur via le nouveau module. Alors le mail aura pour objet "Annule et remplace".

**Comment by celinelgi** [comment]
Voir commande 89994 - je l'ai modifié en supprimant un composant, puis en ajoutant un nouveau composant => dans aucun des cas le statut de la commande a été modifié...il est resté à 'Validation Graphique''

**Comment by MamboJoel** [comment]
Tu voulais que l'ancienne appli ne passe plus au statut "Envoyé à l'imprimeur" lorsqu'un des événements listés plus haut est levé. C'est ce qu'on a fait.

**Comment by MamboJoel** [comment]
Quand on passe la commande en projet dans l'ancienne appli, la repasser en projet dans la nouvelle.

**Comment by MamboJoel** [comment]
Ok : j'ai effectué le correctif. Désormais quand dans l'ancienne tu repasses en projet, la commande repasse en projet dans la nouvelle. Le scénario est le suivant :
- Tu effectues ta série de changement dans l'ancienne appli.
- Dans la nouvelle tu constates que la commande est en Projet.
- Tu l'envoies à l'imprimeur.
- Il reçoit le mail "Annule et remplace".

Ça colle ?

**Comment by celinelgi** [comment]
Exemple - Cdde# 90593 Romain a fait des modification et lorsqu'il a renvoyé la nouvelle version de la commande  à Barat le terme ''Annule et Remplace'' ne s'est pas inséré automatiquement
![image](https://cloud.githubusercontent.com/assets/22617509/20483278/79410214-aff1-11e6-9440-2b0b35fa7f89.png)

**Comment by celinelgi** [comment]
Annule & Remplace ne fonctionne pas exemple # 90674
