### ISSUE TITLE
PRIX BUDGET IMPRIMEUR 

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#73]
Attention, je vois sur le profil de Virginie, qu'elle peut voir nos prix budget, cf. cdde # 89994
Il ne faut surtout pas qu'elle ait accès à ces données car cela pourrait mettre en danger nos négo de prix
Cf commentaire d'entrée de l'issue 'Visibilité des champs''

**Comment by MamboJoel** [comment]
Ok !

**Comment by celinelgi** [comment]
Ca ne fonctionne toujours pas!
On étant loguée sous Virginie Moreau, je vois toujours le prix budget, exemples de commandes # 90304 & 90341

**Comment by MamboJoel** [comment]
Étonnant, je ne le vois pas chez moi... Je me demande si ça n'est pas encore une histoire de cache.

![virginie moreau](https://cloud.githubusercontent.com/assets/3832009/20272770/3ba249e8-aa8f-11e6-975e-0f9617c039b7.png)

**Comment by MamboJoel** [comment]
Ah, tu parles peut-être du récap en haut à droite ? On a fait la modif au niveau des lignes de commande simplement.

**Comment by celinelgi** [comment]
non dans les lignes de composants voir impr ecran
![image](https://cloud.githubusercontent.com/assets/22617509/20272934/cf6603e0-aa8f-11e6-8786-535cad7d6b1d.png)
