### ISSUE TITLE
Gestions Alertes Emails autres utilisateurs depuis compte Céline

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#76]
J'ai essayé de modifier les paramètres de réception des emails de Virginie, Romain & Eric, il semblerait que la modification apportée aux paramètres de Romain ait impacté les paramètres d'Eric et Virginie...
Pour résumé!
Romain voulait recevoir uniquement des alertes emails lorsque la commande passe en statut ''BAT/Devis Publiés", lorsque j'ai modifié les paramètres de Virginie pour recevoir les alertes uniquement en statut 'envoyée à 'imprimeur' et 'Validée'', cela a également modifié les paramètres de Romain....

**Comment by MamboJoel** [comment]
On a fait plusieurs modifications derrière le formulaire de l'utilisateur. Actuellement seuls les users avec droit d'accès sécurité pouvaient modifier les users. Ca empêchait donc Virginie de modifier ses données d'envoi de mails. On a ouvert l'accès aux users sur leurs propres données donc les imprimeurs peuvent eux-même paramétré leur compte.
Je ne reproduis pas l'anomalie que tu remontes. Il est probable que nos modifications l'aient effacées.

**Comment by celinelgi** [comment]
J'ai vidé mon historique complet de Google Chrome avant de faire les test
Je confirme que cela fonctionne bien depuis le compte de Virginie Moreau (j'ai modifié son adresse email pour mon adresse Marketing afin de voir ce que je recevais)
En parallèle, j'ai modifié mon compte pour être alertée par email que sur certains statuts, puis aucun, cependant je reçois des emails à tous les statuts de la commande
J'ai utilisé la commande 89994

**Comment by celinelgi** [comment]
En ce qui concerne la modification des paramètres utilisateurs depuis mon compte, cela ne fonctionne toujours pas... J'ai reproduit le problème pour les comptes de Romain et Virginie
Lorsque je suis sur la console de paramètrage, dès lors que je modifie les paramètres d'un compte, cela modifie ceux des autres utilisateurs...

**Comment by MamboJoel** [comment]
Pour autant ils ont des paramétrages différents :

![image](https://cloud.githubusercontent.com/assets/3832009/20383616/c7e6859a-acb0-11e6-91ac-e27505183eca.png)

![image](https://cloud.githubusercontent.com/assets/3832009/20383625/d0d7a666-acb0-11e6-99c3-d258bb4e5780.png)

**Comment by MamboJoel** [comment]
Je pense que pour reproduire ton anomalie il fallait passer par "Utilisateurs" puis la liste déroulante. Je me loguait en tant que Virginie puis toi et je cliquais sur le nom en haut à droite pour obtenir le formulaire. Ce scénario ne reproduit pas d'anomalie.

Cela dit, même en passant par la liste déroulante je ne reproduis pas l'anomalie d'une affectation à tous les utilisateurs des sélection d'un seul. Mais j'ai d'autres erreurs, comme par exemple une liste de statuts de commande vide.

J'ai remis de l'ordre dans cette page, c'est sûrement corrigé. En tout cas je ne reproduis pas.

Quant à l'autre problème : que tu reçois tous les mails. C'est parce que pour tester on avait configuré l'envoi de mail systématique à l'expéditeur. On l'a retiré.
