### ISSUE TITLE
Joindre un fichier

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#77]
Lorsque l'on ajoute plusieurs fichiers les uns après les autres, le déroulants ''Joindre un fichier' passe derrière le bouton envoyer, voir impr écran ci-dessous
![image](https://cloud.githubusercontent.com/assets/22617509/20311626/c9174654-ab50-11e6-958b-4aef7d80a8a2.png)

**Comment by MamboJoel** [comment]
Ok.
