### ISSUE TITLE
Moteur de Recherche - Satut Projet

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#79]
Lorsque je fais une recherche uniquement par le statut Projet, rien ne remonte, alors qu'il y a beaucoup de commandes encore au statut projet...

**Comment by MamboJoel** [comment]
Je ne reproduis pas.
Je cherche comme ça :
- Statut : Projet
- Du : 25 octobre 2016
- A aujourd'hui
Et j'obtiens de nombreuses commandes.

Tu peux peut-être me désigner une recherche donnée et une commande que tu en attends afin que je reproduise l'anomalie.
