### ISSUE TITLE
Commande - Infos Embouteilleur du formulaire composant

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#80]
Peux-tu faire remonter l'info de l'embouteilleur qui est dans le formulaire?

**Comment by MamboJoel** [comment]
Peux-tu préciser ? 

- Tu veux qu'on remonte l'embouteilleur du composant ?

Ici UCC :

![image](https://cloud.githubusercontent.com/assets/3832009/20929569/dbf41eca-bbca-11e6-89f4-87cf5d5a350e.png)

- Et où veux-tu qu'on le remonte ? Sur l'UI, sur le PDF ?

**Comment by celinelgi** [comment]
OUi
