### ISSUE TITLE
Commande - Ajouter sens enroulement et diamètre bobine

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#88]
Ces deux notions apparaissent sur nos BAT, jusqu'à maintenant jamais sur nos bon de commande. Cependant, ces informations sont très importantes, et nos imprimeurs nous les demandent.

Ces deux notions sont conditionnées au niveau du centre d'embouteillage.
Est-ce possible d'intégrer ces champs au niveau de l'embouteilleur?
Ex: champs Enroulement avec cases à cocher (Extérieur droit, Extérieur, Gauche, Intérieur Droit, Intérieur Gauche)
Diamètre (mm): champs numérique

Ensuite, ces informations doivent apparaître sur la commande dès lors que au moins un des composant a pour collage 'adhésif'

**Comment by MamboJoel** [comment]
Il existe déjà un commentaire embouteilleur qui est défini au niveau de l'embouteilleur et qui apparaît sur la commande. C'est un typage très laxiste qui permet de transmettre n'importe quel type d'information.

A l'inverse cette demande appelle un typage très fin (une série de booléens et champ numérique), ainsi qu'un test en sortie. Vous la confirmez ?

**Comment by celinelgi** [comment]
On confirme, as-tu besoin de complément d'infos?

**Comment by celinelgi** [comment]
Il faut ajouter deux nouveaux champs ouverts dans l'ancien Waybis dans le formulaire de l'embouteilleur:
- Sens d'enroulement (liste à créer: extérieur gauche / intérieur droit / extérieur droit / intérieur gauche) + Image à télécharger
- Diamètre bobine (cm)

**Comment by MamboJoel** [comment]
@Portekoi je pense que tu peux traiter cette issue.
Il s'agit d'ajouter trois champs à la table et à la class `Bottler` :

- `WindingDirection` (sens d'enroulement), string. Mais se présentera dans la page en liste de sélection parmi les choix :
extérieur gauche / intérieur droit / extérieur droit / intérieur gauche
- `WindingDirectionImage `: une image à uploader dans le répertoire `Web/Uploads/BottlerWinding` à créer (tu peux t'inspirer de `Waybis.Pinard.Component.UploadImage()` pour créer une fonction `Waybis.Pinard.Bottler.UploadWindingImage()`.)
- `SpoolDiameter `(diamètre bobine (cm)), `decimal`, précision de deux.

Et les interfacer dans la page `Web/Bottler/Form.aspx `(en t'inspirant pour l'upload de `Web/UserControls/LabelForm.ascx`)

N'hésite pas si t'as des questions.

**Comment by celinelgi** [comment]
@Portekoi
