### ISSUE TITLE
Statuts consultables par imprimeurs

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#89]
Les statuts 'reçue'/'facturée' ne doivents pas être visibles des imprimeurs au même titre que le statut 'projet'.
Je remarque que Vmoreau de Barat voit tous les statuts versus Apicard de Aset.
Il faut uniformiser, SVP et se caler sur le compte d'Almeria Picard.

**Comment by MamboJoel** [comment]
Je ne reproduis pas.
![image](https://cloud.githubusercontent.com/assets/3832009/20926534/15ba7400-bbbd-11e6-83f2-be914d3e153e.png)
Peut-être un vieux cache subsiste-t-il chez Almeria Picard.
