### ISSUE TITLE
Commande VALIDEE => message de validation

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#91]
Attention le numéro de la commande ne remonte pas dans le texte du message email, je te transfère l'exemple sur Cdde# 90674

Le message de validation de la commande doit également apparaître dans le suivi de la commande, avec possibilité de télécharger/imprimer le message.

**Comment by MamboJoel** [comment]
- Le numéro de commande apparaît toujours dans les emails.
- On a fait des recherches pour intégrer des mails dans des pages web, ce qui n'est pas le processus habituel. Maintenant le message de validation apparaît quasi comme le mail de validation.
