### ISSUE TITLE
Bugs Statuts sur commandes

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#95]
Ex cdde# 87581 cette commande est en statut Devis BAT Publié alors qu'elle est reçue depuis juillet.
Il y a plusieurs commandes dans ce cas de figure

**Comment by MamboJoel** [comment]
J'ai fait des recherches et je pense qu'il y a deux sources à ce problème.

Voici la liste des commandes "Reçue" coté extranet et qui ne sont pas en "Commande reçue" coté ui :

![image](https://cloud.githubusercontent.com/assets/3832009/20923955/3d8ecd0e-bbaf-11e6-872e-372d68daa99e.png)
![image](https://cloud.githubusercontent.com/assets/3832009/20924007/8bd893be-bbaf-11e6-9cdc-e06b3cc52c58.png)

- La 87581 fait partie des huit premières, datent de cet été, et sont clairement un reliquat du déploiement et des diverses modification de statuts qui en ont suivi.
- Les suivantes sont plus suspectes car elles courent jusque la mi-novembre, mais plus aucune occurrence n'est survenue depuis le 14. Je suppose qu'une mise à jour empêche l'anomalie d'être levée à nouveau.

J'ai manuellement passé en "Commande reçue" ces 44 commandes.
