### ISSUE TITLE
Commandes en statut VALIDEE

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#97]
Attention il faut que les commandes soient figées dès lors qu'elles sont validées.
Si nous souhaitons les modifier après-coup il faudra changer son statut.

Actuellement les commandes VALIDEES ne sont pas figées

**Comment by MamboJoel** [comment]
OK.

**Comment by celinelgi** [comment]
Attention exemple cdde 90729, j'ai modifié la quantité 5000 à 0, et la commande a été modifié malgré son stattu Validé
