### ISSUE TITLE
Bug cdde # 90649

### ISSUE THREAD

**Issue by celinelgi** [lgi-wines/Approvisionnements#99]
90649 - sur cette commande nous ne pouvons plus rien faire, exemple le suivi

**Comment by celinelgi** [comment]
autre exemple 90770

**Comment by celinelgi** [comment]
Suite à l'ouverture de la commande # 90770 lorsque je clique sur commande tout en haut dans la barre bleue je reviens sur le dashboard mais on ne peut plus rien faire... il faut que je ferme le module appro et que je me reconnecte.

**Comment by MamboJoel** [comment]
Je l'ai trouvé et corrigé.

**Comment by MamboJoel** [comment]
Avec F5 tu mettras à jour les scripts.
